version: '2'
services:
  database:
    build:
      context: ./21.3.0/
      dockerfile: Dockerfile.xe
    volumes:
       - C://Users/Duarte/Documents/Repositories-data:/data/oracle/oradata # persistent oracle database data.
    ports:
      - 1521:1521
      - 8080:8080
      - 5500:5500