CREATE OR REPLACE FUNCTION F03_EX08
(CODAUTOR AUTORES.CODIGO_AUTOR%TYPE)
RETURN VARCHAR
IS

	VNOME AUTORES.NOMEC%TYPE;
BEGIN
	SELECT nome INTO VNOME
	FROM AUTORES a
	WHERE CODIGO_AUTOR = CODAUTOR;
	NOME := TRIM( SUBSTR(NOME,1,INSTR(NOME,'')));

	RETURN VNOME;

	EXCEPTION WHEN
		NO_DATA_FOUND THEN
			 RAISE_APPLICATION_ERROR(-20302,'Código de autor inexistente.');
END;


CREATE OR REPLACE FUNCTION F03_EX09
(CODAUTOR AUTORES.CODIGO_AUTOR%TYPE)
RETURN VARCHAR
IS
	BCOUNT NUMBER(10);

BEGIN
	SELECT COUNT(L.CODIGO_LIVRO) INTO BCOUNT FROM LIVROS l  WHERE L.CODIGO_AUTOR  = CODIGO_AUTOR;

	IF(BCOUNT <= 0) THEN
		 RAISE_APPLICATION_ERROR(-20304,'O autor com o código ' || CODAUTOR || ' não escreveu livros');
	END IF

	RETURN BCOUNT;
END;

