CREATE OR REPLACE  TRIGGER F04_EX06
AFTER INSERT OR DELETE OR UPDATE OF GENERO,PRECO_TABELA ON LIVROS
BEGIN
	F04_EX05;
END;

CREATE OR REPLACE TRIGGER F04_EX07
BEFORE DELETE ON AUTORES
REFERENCING OLD AS o NEW AS n
FOR EACH ROW
BEGIN
	DELETE FROM LIVROS l WHERE l.CODIGO_AUTOR = :OLD.CODIGO_AUTOR;
END;

CREATE OR REPLACE TRIGGER F05_EX11
AFTER INSERT ON VENDAS
REFERENCING OLD AS o NEW AS n
FOR EACH ROW
DECLARE
	TOTAL_STOCK_NEW NUMBER;
BEGIN
	TOTAL_STOCK_NEW :=  L.QUANT_EM_STOCK- :NEW.QUANTIDADE;
	UPDATE LIVROS l SET l.QUANT_EM_STOCK = TOTAL_STOCK_NEW WHERE L.CODIGO_LIVRO = :NEW.CODIGO_LIVRO;
END;