

BEGIN
	INSERT INTO NETWORK (NAME,DIGITS_COUNT,PREFIX) VALUES ('Fixo Nacional','9','2xxxxxxxx');
	INSERT INTO NETWORK (NAME,DIGITS_COUNT,PREFIX) VALUES ('Móvel Nacional','9','9xxxxxxxx');
	INSERT INTO NETWORK (NAME,DIGITS_COUNT,PREFIX) VALUES ('Móvel Nacional','9','808xxxxxx');
	INSERT INTO NETWORK (NAME,DIGITS_COUNT,PREFIX) VALUES ('Gratuito','14','003512xxxxxxxx');
	INSERT INTO NETWORK (NAME,DIGITS_COUNT,PREFIX) VALUES ('Internacional','>3','00x...');
END;